version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
  typescript: vidsy/typescript@1.2.1
jobs:
  aws-cli-setup:
    working_directory: ~/repo
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: aws s3 ls 
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install np dependencies
          command: |
            npm install --save
      - run: node bin/s3Bucket.ts

workflows:
  aws-cli:
    jobs:
      - aws-cli-setup:
          context: aws
      - run_tests


