version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-setup:
    working_directory: ~/repo
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: aws s3 ls 
workflows:
  aws-cli:
    jobs:
      - aws-cli-setup:
          context: aws