version: '2.1'

executors:
  default:
    docker:
      - image: 'circleci/node:14.2.0'
    environment:
      AWS_REGION: 'eu-west-1'
jobs:
  build:
    executor: 'default'
    steps:
      - run:
          name: 'assume_role'
          command: |
            sudo apt-get install awscli
            unset AWS_SESSION_TOKEN
            echo $ASSUME_ROLE_ARN
            echo "export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)" >> $BASH_ENV
      - checkout
      - run:
          name: 'build'
          command: |
            npm install
            npm run build
            npm install cdk
            npm cdk deploy


