version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-setup:
    working_directory: ~/repo
    executor: aws-cli/node
    steps:
      - checkout
      - aws-cli/install
      - run: aws s3 ls 
  main:
    steps:
      - checkout
      - ts-node bin/s3Bucket.ts
      - node bin/s3Bucket.js

workflows:
  aws-cli:
    jobs:
      - aws-cli-setup:
          context: aws