version: '2.1'
# orbs:
#   aws-cli: circleci/aws-cli@2.0
#   typescript: vidsy/typescript@1.2.1
# jobs:
#   aws-cli-setup:
#     working_directory: ~/repo
#     executor: aws-cli/default
#     steps:
#       - checkout
#       - aws-cli/install
#       - run: aws s3 ls 
#   run-code:
#     working_directory: ~/repo
#     executor: typescript/default
#     steps:
#       - checkout
#       - run: node bin/s3Bucket.js

# workflows:
#   aws-cli:
#     jobs:
#       - aws-cli-setup:
#           context: aws

jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
        name: Install np dependencies
        comand: |
          npm install --save
      run: node bin/s3Bucket.ts

workflow:
  build_test:
    jobs:
      - run tests